CREATE TABLE IF NOT EXISTS tags (
    id INT AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    subtitle VARCHAR(200) NOT NULL,
    PRIMARY KEY(id)

) 
CREATE TABLE IF NOT EXISTS questions_group (
    id INT AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    subtitle VARCHAR(200) NOT NULL,
    PRIMARY KEY(id)

) 